---
services:
  telegraf:
    image: drew1kun/telegraf:1.39.0-alpine@sha256:cd1398ea16eedc2a31ba20380ab0a49c614bfdbb90a6e41c85cb97da2bb7a806
    restart: unless-stopped
    privileged: true
    networks:
      - umbrel_main_network
    group_add:
      - ${DOCKER_GID}
    volumes:
      - ${APP_DATA_DIR}/data/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ${APP_DATA_DIR}/data/config/telegraf.d:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/sbin/nvme:/usr/sbin/nvme:ro
      - /:/hostfs:ro
    env_file:
      - ${APP_DATA_DIR}/.env
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      UMBREL_HOSTNAME: ${UMBREL_HOSTNAME}
      UMBREL_SEARCH_DOMAIN: ${UMBREL_SEARCH_DOMAIN:-local}
    command:
      - telegraf
      - --config
      - /etc/telegraf/telegraf.conf
      - --config-directory
      - /etc/telegraf/telegraf.d

networks:
  umbrel_main_network:
    external: true
